# Generated by Django 5.1.6 on 2025-05-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerorder",
            name="country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customerorder",
            name="state",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
