# Generated by Django 5.1.6 on 2025-09-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_item_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="brand",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(editable=False, max_length=120, unique=True),
        ),
    ]
