# Generated by Django 5.1.6 on 2025-09-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_item_brand_alter_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name="itemimage",
            name="image",
            field=models.ImageField(upload_to="items/extra/"),
        ),
    ]
