# Generated by Django 5.1.6 on 2025-09-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_category_slug_alter_itemimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(editable=False, max_length=120, unique=True),
        ),
    ]
