# Generated by Django 5.1.6 on 2025-05-27 19:04

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                default="default_avatars/default.png",
                null=True,
                upload_to=accounts.models.user_profile_pic_path,
            ),
        ),
    ]
